import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { signIn, useSession, signOut } from 'next-auth/react';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  const { data } = useSession();

  const handleLogin = () => {
    signIn('discord');
  };

  const handleLogout = () => {
    signOut();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          {!data ? (
            <div>
              <h1>Not logged in</h1>
              <Link href='/auth/signIn'>
                <button>
                  Login
                </button>
              </Link>
            </div>
          ) : null}
          {data?.user?.name ? (
            <div>
              <h1>Welcome {data.user.name}</h1>
              <div>
                <Image
                  src={data.user.image as string}
                  width={100}
                  height={100}
                  alt='user-image'
                />
              </div>
              <button onClick={handleLogout}>Logout</button>
            </div>
          ) : null}
          <div style={{ marginTop: '2rem' }}>
            <Link href='/protected'>
              <button>
                Navigate to the Protected page
              </button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
